version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bitcoin-treasury-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=/app/data/treasury.db
      - COINGECKO_API_URL=https://api.coingecko.com/api/v3
      - YAHOO_FINANCE_API_URL=https://query1.finance.yahoo.com/v8/finance
      - BITCOIN_TREASURIES_URL=https://bitcointreasuries.net
      - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
      - BITCOIN_PRICE_UPDATE_INTERVAL=30
      - STOCK_PRICE_UPDATE_INTERVAL=30
      - HOLDINGS_UPDATE_INTERVAL=360
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
    networks:
      - bitcoin-treasury-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bitcoin-treasury-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - bitcoin-treasury-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  backend_data:
    driver: local
  backend_logs:
    driver: local

networks:
  bitcoin-treasury-network:
    driver: bridge