version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: ${COMPOSE_PROJECT_NAME}-app
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    init: true
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_PATH=${DATABASE_PATH}
      - COINGECKO_API_URL=${COINGECKO_API_URL}
      - YAHOO_FINANCE_API_URL=${YAHOO_FINANCE_API_URL}
      - BITCOIN_TREASURIES_URL=${BITCOIN_TREASURIES_URL}
      - USER_AGENT=${USER_AGENT}
      - BITCOIN_PRICE_UPDATE_INTERVAL=${BITCOIN_PRICE_UPDATE_INTERVAL}
      - STOCK_PRICE_UPDATE_INTERVAL=${STOCK_PRICE_UPDATE_INTERVAL}
      - HOLDINGS_UPDATE_INTERVAL=${HOLDINGS_UPDATE_INTERVAL}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
      - DOMAIN=${DOMAIN}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ${APP_DATA_PATH}:/app/data
      - ${APP_LOGS_PATH}:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
      start_period: ${HEALTH_CHECK_START_PERIOD}